apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhookapi
  name: webhook-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: webhookapi
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhookapi
  labels:
    app: webhookapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhookapi
  template:
    metadata:
      labels:
        app: webhookapi
    spec:
      containers:
      - name: webhookapi
        image: jonsy13/webhookapi:latest
        ports:
        - containerPort: 8081